imports:
    txn-examples: t/data/

git module txn-examples:
    url: git://github.com/atweiden/txn-examples.git
    rev: 32a124e370d851c4fe93e16deb6fd24d171088c3
    drop:
        - README.md
        - UNLICENSE
        - .gitignore
        - .hgignore
        - "*.sh"
